### 원문 벡터 db + QA 벡터 DB -> 답변 평가 후 -> HyDE 재실행
```
extract_queries → split_queries → tool → qa_tool → basic 
→ evaluate ── good → END
            └─ bad → hyde → tool → qa_tool → basic → evaluate → END
```

In [1]:
from pathlib import Path
import sys

root = Path.cwd()
while not (root / "utils_v9").exists() and root != root.parent:
    root = root.parent
sys.path.insert(0, str(root))

from utils_v9.main3 import (run_langraph)

C:\Users\playdata\Documents\1_ai\LLM_hybrid\utils_v9\retriever.py:51: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-chroma package and should be used instead. To use it run `pip install -U :class:`~langchain-chroma` and import as `from :class:`~langchain_chroma import Chroma``.
  vs = Chroma(

In [2]:
from utils_v9.langgraph_setting2 import graph_setting

graph = graph_setting()

graph

ValueError: Failed to reach https://mermaid.ink/ API while trying to render your graph. Status code: 502.

To resolve this issue:
1. Check your internet connection and try again
2. Try with higher retry settings: `draw_mermaid_png(..., max_retries=5, retry_delay=2.0)`
3. Use the Pyppeteer rendering method which will render your graph locally in a browser: `draw_mermaid_png(..., draw_method=MermaidDrawMethod.PYPPETEER)`

In [3]:
response = run_langraph('Firebase의 updateTime 필드에 사용되는 시간 형식이 뭐야?', '1', None)

run_langraph 호출 - 입력: Firebase의 updateTime 필드에 사용되는 시간 형식이 뭐야?, 이미지: False
analyze_image 호출됨 - 이미지 존재: False
[tool_based_search_node] 실행 - queries=['Firebase의 updateTime 필드에 사용되는 시간 형식은 무엇인가요?', 'What is the time format used in the updateTime field of Firebase?']
원문 retriever 생성 완료
QA retriever 생성 완료

C:\Users\playdata\Documents\1_ai\LLM_hybrid\utils_v9\langgraph_node2.py:201: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use :meth:`~invoke` instead.
  results_text = retriever.get_relevant_documents(query)

원문 검색 결과: 길이 14개, 첫 문서: | Fields |
| --- |
| name | string The resource name of the Database. Format: projects/{project}/dat
QA 검색 결과: 길이 23개, 첫 문서: Q: Firestore 문서의 생성 시간(createTime)과 업데이트 시간(updateTime)의 형식은 어떻게 되나요?
A: 두 시간 모두 RFC 3339 형식을 사용하며,
[vector_search_tool] hybrid 검색 완료: 'Firebase의 updateTime 필드에 사용되는 시간 형식은 무엇인가요?', tags=['firestore']
원문 retriever 생성 완료
QA retriever 생성 완료
원문 검색 결과: 길이 13개, 첫 문서: | Fields |
| --- |
| name | string The resource name of the Database. Format: projects/{project}/dat
QA 검색 결과: 길이 24개, 첫 문서: Q: Cloud Firestore 데이터베이스의 업데이트 시간을 확인하는 방법은 무엇인가요?
A: 데이터베이스의 업데이트 시간은 `updateTime` 필드에서 확인할 수 있습니다
[vector_search_tool] hybrid 검색 완료: 'What is the time format used in the updateTime field of Firebase?', tags=['firestore']

In [4]:
print(response['answer'])

Firebase의 `updateTime` 필드는 RFC 3339 형식을 사용합니다. 이 형식은 항상 Z-normalized되며 0, 3, 6 또는 9의 소수 자릿수를 사용할 수 있습니다. 예시로는 "2014-10-02T15:01:23Z", "2014-10-02T15:01:23.045123456Z" 또는 "2014-10-02T15:01:23+05:30"가 있습니다.

In [5]:
response = run_langraph('GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?', '1', None)
print(response)

run_langraph 호출 - 입력: GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?, 이미지: False
analyze_image 호출됨 - 이미지 존재: False
[tool_based_search_node] 실행 - queries=['GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?', 'What does the point (0, 0) represent in the GMSMapPoint coordinate system?']
원문 retriever 생성 완료
QA retriever 생성 완료
원문 검색 결과: 길이 16개, 첫 문서: GMSProjection [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Cl
QA 검색 결과: 길이 25개, 첫 문서: Q: GMSProjection 클래스는 어떤 기능을 제공하나요?
A: GMSProjection 클래스는 지구 좌표 CLLocationCoordinate2D와 맵 뷰의 좌표 CGPo
[vector_search_tool] hybrid 검색 완료: 'GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?', tags=['map']
원문 retriever 생성 완료
QA retriever 생성 완료
원문 검색 결과: 길이 16개, 첫 문서: GMSProjection [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Cl
QA 검색 결과: 길이 25개, 첫 문서: Q: GMSProjection 클래스는 어떤 기능을 제공하나요?
A: GMSProjection 클래스는 지구 좌표 CLLocationCoordinate2D와 맵 뷰의 좌표 CGPo
[vector_search_tool] hybrid 검색 완료: 'What does the point (0, 0) represent in the GMSMapPoint coordinate system?', tags=['map']

In [6]:
print(response['answer'])
# # print(response['tool_calls'])
# print(response['qa_tool_calls'])

GMSMapPoint의 좌표계에서 (0, 0)은 Google 지도에서 메르카토르 투영의 원점, 즉 경도 180도와 위도 약 85도에 있는 지도의 북서쪽 모서리를 의미합니다. 이 지점에서 x 방향으로 동쪽(오른쪽)으로 증가하고, y 방향으로 남쪽(아래쪽)으로 증가합니다.

In [7]:
response = run_langraph('MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일에 직접해야 하나요?', '1', None)

run_langraph 호출 - 입력: MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일에 직접해야 하나요?, 이미지: False
analyze_image 호출됨 - 이미지 존재: False
[tool_based_search_node] 실행 - queries=['MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일을 직접 수정해야 하나요?', 'Do I need to directly modify the config.json file to configure the cover of MAP 3D storytelling?']
원문 retriever 생성 완료
QA retriever 생성 완료
원문 검색 결과: 길이 16개, 첫 문서: downloadJSON 스키마 다운로드 [https://developers.google.com/static/maps/cbms-json-schema.json?hl=ko]
스타일 편집
QA 검색 결과: 길이 22개, 첫 문서: Q: JSON 스타일 지정을 사용하여 지도를 수동으로 맞춤설정하는 방법은 무엇인가요?
A: 지도를 수동으로 맞춤설정하면 일반 지도 유형의 스타일을 지정할 수 있으며 지도 ID가 필
[vector_search_tool] hybrid 검색 완료: 'MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일을 직접 수정해야 하나요?', tags=['map']
원문 retriever 생성 완료
QA retriever 생성 완료
원문 검색 결과: 길이 16개, 첫 문서: assignment [https://developers.google.com/maps/architecture/3d-storytelling-customizations?hl=ko]
맞춤
QA 검색 결과: 길이 23개, 첫 문서: Q: JSON 스타일 지정을 사용하여 지도를 수동으로 맞춤설정하는 방법은 무엇인가요?
A: 지도를 수동으로 맞춤설정하면 일반 지도 유형의 스타일을 지정할 수 있으며 지도 ID가 필
[vector_search_tool] hybrid 검색 완료: 'Do I need to directly modify the config.json file to configure the cover of MAP 3D storytelling?', tags=['map']

In [8]:
print(response['answer'])

죄송하지만, 제공된 문서에는 "MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일에 직접해야 하는지"에 대한 정보가 포함되어 있지 않습니다. 따라서 이 질문에 대한 답변을 제공할 수 없습니다. 다른 질문이 있으시면 말씀해 주세요.

In [9]:
## 환경설정
# !pip install -qU ragas langchain langchain-community langchain-openai langchain-chroma langchain-text-splitters pypdf rapidfuzz langgraph gdown chromadb langchain-huggingface sentence-transformers -q

In [7]:
# !pip install ragas

In [10]:
import os
from dotenv import load_dotenv

load_dotenv()
# 필요한 라이브러리 임포트
import os
import pandas as pd
from pprint import pprint
# LangChain 관련 라이브러리
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
# RAGAS 관련 라이브러리
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.testset.persona import Persona
from ragas.testset import TestsetGenerator
from ragas import EvaluationDataset, evaluate
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness

## 이미 생성된 합성 데이터셋 생성

In [11]:
import pandas as pd

# 같은 폴더(현재 작업 디렉토리)에 저장했다면
dataset_df = pd.read_csv("./dataset2.csv")
print(dataset_df.shape)
display(dataset_df)

(20, 4)

,user_input,reference_contexts,reference,synthesizer_name
0,CSV 파일을 이용해서 S/MIME 인증서를 관리하려면 어떤 작업이 필요한가요?,['Q: S/MIME 인증서를 관리하기 위해 CSV 파일을 처리하는 함수에서 어떤 ...,"CSV 파일을 처리하는 함수에서는 사용자의 인증서를 나열하고, 기본 인증서가 만료되...",single_hop_specific_query_synthesizer
1,클라우드 파이어스토어 부하 분산기 어떻게 써야되나요?,['Q: Cloud Firestore의 부하 분산 기능은 어떻게 작동하나요?\nA:...,Cloud Firestore는 데이터베이스에 대한 트래픽을 지원하기 위해 자동으로 ...,single_hop_specific_query_synthesizer
2,범위 많으면 동의 어렵나요?,['Q: OAuth 2.0을 사용할 때 요청하는 범위의 수가 사용자 동의에 미치는 ...,요청된 범위 수가 많으면 사용자 동의를 얻을 가능성이 낮아질 수 있습니다.,single_hop_specific_query_synthesizer
3,As a beginner who is not familiar with Google ...,"['Q: Google Cloud 세션 제어 기능이란 무엇이며, 어떤 영향을 미치나요...",When Google Cloud session control features are...,single_hop_specific_query_synthesizer
4,"firebase_functions 어떻게 쓰는지 잘 모르겠는데, Cloud Fire...",['Q: Cloud Firestore에서 특정 문서의 모든 변경에 대해 이벤트를 트...,Cloud Firestore에서 특정 문서의 모든 변경에 이벤트를 트리거하려면 on...,single_hop_specific_query_synthesizer
5,Firebase에서 다단계 인증(MFA)을 사용할 때 Objective-C로 사용자...,['Q: 다단계 인증(MFA) 사용 시 Firebase에서 사용자 인증을 완료하는 ...,다단계 인증(MFA) 사용 시 Firebase에서 사용자 인증을 완료하는 방법은 F...,single_hop_specific_query_synthesizer
6,Java를 사용해서 Firestore에 문서를 추가할 때 어떤 코드를 사용하나요?,['Q: Firestore에서 문서에 데이터를 추가할 때 사용하는 Java 코드 예...,다음은 Java에서 Firestore에 문서를 추가할 때 사용하는 코드 예시입니다....,single_hop_specific_query_synthesizer
7,COLUMNS가 Dimension API에서 무슨 뜻인가요?,['Q: Dimension API에서 사용할 수 있는 열거형 값은 무엇인가요?\nA...,COLUMNS는 Dimension API에서 시트의 열에서 작동함을 의미합니다.,single_hop_specific_query_synthesizer
8,ttll이 뭐에요? 그리고 한도 같은거 있나요?,['Q: TTL 정책을 적용할 때 한도 및 제약조건은 무엇인가요?\nA: 컬렉션 그...,"컬렉션 그룹당 하나의 필드만 TTL 필드로 표시할 수 있고, 필드 수준 구성은 최대...",single_hop_specific_query_synthesizer
9,Me want know what FUNCTION_ENTRYPOINT do in gc...,['Q: gcloud CLI를 사용하여 Cloud Run 함수를 배포한 후 트리거를...,FUNCTION_ENTRYPOINT는 gcloud run deploy 명령어에서 함...,single_hop_specific_query_synthesizer
10,Google 피트니스 심박수 데이터 읽기 권한 범위는?,['Q: Google 피트니스에서 심박수 데이터를 확인하기 위해 필요한 OAuth ...,Google 피트니스에서 심박수 데이터를 확인하기 위해 필요한 OAuth 2.0 범...,single_hop_specific_query_synthesizer
11,projets.databeses.gte 메서드 쓸때 HTTP 리퀘스트 포맷이 뭐에요?,['Q: projects.databases.get 메서드를 호출할 때 필요한 HTT...,HTTP 요청 형식은 다음과 같습니다:\r\n```\r\nGET https://fi...,single_hop_specific_query_synthesizer
12,Google Developers Console을 활용하여 YouTube Data A...,['Q: YouTube Data API를 사용 설정하기 위한 첫 번째 단계는 무엇인...,YouTube Data API를 사용 설정하기 위한 첫 번째 단계는 Google D...,single_hop_specific_query_synthesizer
13,firsetore users 데이타 가져오려면 어떻게하나요? users 콜렉션에서 ...,['Q: Firestore에서 데이터를 가져오는 방법은 무엇인가요?\nA: Fire...,Firestore에서 users 콜렉션의 모든 users 정보를 가져오려면 다음과 ...,single_hop_specific_query_synthesizer
14,Python에서 Cloud Firestore 초기화 방법,"[""Q: Cloud Firestore를 Python에서 서비스 계정을 사용하여 초기...",Cloud Firestore를 Python에서 서비스 계정을 사용하여 초기화하려면 ...,single_hop_specific_query_synthesizer
15,"BigQuery에서 쿼리 실행 단계의 병렬 입력 세그먼트 수를 확인하고자 할 때, ...","[""Q: BigQuery에서 쿼리 실행 단계의 병렬 입력 세그먼트 수를 확인하려면 ...",BigQuery에서 쿼리 실행 단계의 병렬 입력 세그먼트 수를 확인하려면 'para...,single_hop_specific_query_synthesizer
16,itemDownlodRestrction 뭐에요?,"[""Q: 파일의 다운로드 제한이 소유자 또는 주최자가 직접 적용한 것인지 확인하려면...",itemDownloadRestriction 필드는 소유자 또는 주최자가 직접 적용한...,single_hop_specific_query_synthesizer
17,What does the textFormat field represent in Tr...,['Q: TreemapChartSpec의 JSON 표현에서 textFormat 필드...,The textFormat field specifies the text format...,single_hop_specific_query_synthesizer
18,fileId는 무엇을 의미하나요?,['Q: AccessProposal을 ID로 검색하는 API 요청은 어떻게 하나요?...,fileId는 파일의 ID를 의미합니다.,single_hop_specific_query_synthesizer
19,"Gmail 작업을 선언하는 방법에 대해 자세히 알고 싶은데, Declaring Ac...",['Q: Gmail의 작업 선언 방법에 대한 자료는 어디에서 찾을 수 있나요?\nA...,작업 선언 방법에 대한 자세한 내용은 작업 선언(Declaring Actions) ...,single_hop_specific_query_synthesizer

In [16]:

## 02.RAG 체인 구성

import pandas as pd
from datasets import Dataset
import uuid
import time


evaluated_dataset = []

for _, row in dataset_df.iterrows():
    time.sleep(3)
    query = row.user_input  # 사용자 입력 - 합성 데이터셋에서 가져옴

    # run_langraph 함수 호출
    rag_result = run_langraph(query,'1', None)

    evaluated_dataset.append(
        {
            "user_input": query,
            "retrieved_contexts": [doc for doc in rag_result["search_results_final"]],
            "response": rag_result["answer"],
            "reference": row['reference']
        }
    )

print("평가 데이터셋 준비 완료")

# RAGAS 평가 데이터셋 생성
ragas_evaluated_dataset = Dataset.from_list(evaluated_dataset)
# csv 데이터 저장
# ragas_evaluated_dataset.to_pandas().to_csv('ragas_evaluated_dataset_hybrid4.csv', index=False)
ragas_evaluated_dataset.to_pandas().info()

run_langraph 호출 - 입력: CSV 파일을 이용해서 S/MIME 인증서를 관리하려면 어떤 작업이 필요한가요?, 이미지: False
analyze_image 호출됨 - 이미지 존재: False
[tool_based_search_node] 실행 - queries=['CSV 파일을 사용하여 S/MIME 인증서를 관리하는 방법은 무엇인가요?', 'How can I manage S/MIME certificates using a CSV file?']
원문 retriever 생성 완료
QA retriever 생성 완료
원문 검색 결과: 길이 10개, 첫 문서: except (OSError, IOError) as error:
    print(f"An error occured while reading the CSV file: {error}
QA 검색 결과: 길이 20개, 첫 문서: Q: 여러 사용자의 S/MIME 인증서를 한 번에 관리하기 위해 어떤 방법을 사용할 수 있나요?
A: 여러 사용자의 S/MIME 인증서를 한 번에 관리하기 위해 CSV 파일을 사용
[vector_search_tool] hybrid 검색 완료: 'CSV 파일을 사용하여 S/MIME 인증서를 관리하는 방법은 무엇인가요?', tags=['gmail']
원문 retriever 생성 완료
QA retriever 생성 완료
원문 검색 결과: 길이 11개, 첫 문서: --- 탭: Python ---
이전의 create_smime_info 및 insert_smime_info 호출을 사용하여 CSV 파일에 지정된 인증서를 업로드할 수 있습니다.


QA 검색 결과: 길이 20개, 첫 문서: Q: 여러 사용자의 S/MIME 인증서를 한 번에 관리하기 위해 어떤 방법을 사용할 수 있나요?
A: 여러 사용자의 S/MIME 인증서를 한 번에 관리하기 위해 CSV 파일을 사용
[vector_search_tool] hybrid 검색 완료: 'How can I manage S/MIME certificates using a CSV file?', tags=['gmail']
[tool_based_search_node] 실행 - state['search_results']=['except (OSError, IOError) as error:\n    print(f"An error occured while reading the CSV file: {error}")\n\n\nif __name__ == "__main__":\n  insert_cert_from_csv(csv_filename="xyz")\n인증서 관리\n이 예에서는 smimeInfo API의 여러 호출을 결합하여 조직의 인증서를 관리하는 방법을 보여줍니다. 사용자의 인증서를 나열하고 기본 인증서가 만료되었거나 설정되지 않은 경우 지정된 파일에서 찾은 인증서를 업로드합니다. 그런 다음 만료일이 가장 늦은 인증서를 기본값으로 설정합니다.\n그런 다음 이전 예와 같이 CSV 파일을 처리하는 함수에서 이를 호출합니다.\n--- 탭: 자바 ---\n.filepath {\n    color: #fff;\n    margin: 6px;\n    max-width: calc(100% - 160px); /* Give at least 160px for the "View on GitHub" button. */\n    text-overflow: ellipsis;\n    text-shadow: rgba(0,0,0,0.1) 1px 1px;\n    overflow: hidden;\n  }\n  .github-docwidget-gitinclude-code .prettyprint {\n    margin: 0;\n  }\n  .view-on-github {\n    text-shadow: rgba(12,12,12,0.1) 1px 1px;\n  }\n\n\n\n  \n  gmail/snippets/src/main/java/UpdateSmimeCerts.java\n  \n    \n    GitHub에서 보기 [https://github.com/googleworkspace/java-samples/blob/main/gmail/snippets/src/main/java/UpdateSmimeCerts.java]', '--- 탭: Python ---\n이전의 create_smime_info 및 insert_smime_info 호출을 사용하여 CSV 파일에 지정된 인증서를 업로드할 수 있습니다.\n\n\n\n\n\n\n\n\n\n\n\n  \n  \n  \n  \n\n\n\n\n\n\n\n\n\n\n\n  .filepath {\n    color: #fff;\n    margin: 6px;\n    max-width: calc(100% - 160px); /* Give at least 160px for the "View on GitHub" button. */\n    text-overflow: ellipsis;\n    text-shadow: rgba(0,0,0,0.1) 1px 1px;\n    overflow: hidden;\n  }\n  .github-docwidget-gitinclude-code .prettyprint {\n    margin: 0;\n  }\n  .view-on-github {\n    text-shadow: rgba(12,12,12,0.1) 1px 1px;\n  }\n\n\n\n  \n  gmail/snippet/smime snippets/insert_cert_from_csv.py\n  \n    \n    GitHub에서 보기 [https://github.com/googleworkspace/python-samples/blob/main/gmail/snippet/smime%20snippets/insert_cert_from_csv.py]\n  \n  \n  \n\n  \n    \n  \n  \n  import csv\n\nimport create_smime_info\nimport insert_smime_info\n\n\ndef insert_cert_from_csv(csv_filename):\n  """Upload S/MIME certificates based on the contents of a CSV file.\n  Each row of the CSV file should contain a user ID, path to the certificate,\n  and the certificate password.\n\n  Args:\n    csv_filename: Name of the CSV file.\n  """', "이 페이지는 Cloud Translation API [https://cloud.google.com/translate/?hl=ko]를 통해 번역되었습니다.\nSwitch to English\n홈 [https://developers.google.com/?hl=ko]\nGoogle Workspace [https://developers.google.com/workspace?hl=ko]\nGmail [https://developers.google.com/workspace/gmail?hl=ko]\n가이드 [https://developers.google.com/workspace/gmail/api/guides?hl=ko]\n의견 보내기\nS/MIME 인증서 관리\nbookmark_border\n이 페이지의 내용\nAPI 액세스 승인\nACL 범위\nAPI 사용\nS/MIME 키 업로드\n사용자의 S/MIME 키 나열\n별칭의 S/MIME 키 가져오기\nS/MIME 키 삭제\n별칭의 기본 S/MIME 키 설정\nGmail S/MIME API는 Google Workspace 도메인의 사용자를 위한 S/MIME 이메일 인증서를 관리할 수 있는 프로그래매틱 액세스를 제공합니다.\n인증서가 작동하려면 관리자가 도메인에 S/MIME을 사용 설정 [https://support.google.com/a/answer/6374496?hl=ko]해야 합니다.\nS/MIME 표준 [https://en.wikipedia.org/wiki/S/MIME]은 공개 키 암호화 및 MIME 데이터 서명에 관한 사양을 제공합니다. 사용자 계정에서 S/MIME 인증서를 구성하면 Gmail에서 다음과 같은 방식으로 해당 인증서를 사용합니다.\nGmail은 사용자의 인증서와 비공개 키를 사용하여 발신 메일에 서명합니다.\nGmail은 사용자의 비공개 키를 사용하여 수신 메일을 복호화합니다.\nGmail은 수신자의 인증서와 공개 키를 사용하여 발신 메일을 암호화합니다.\nGmail은 발신자의 인증서와 공개 키를 사용하여 수신 메일을 확인합니다.\n개별 S/MIME 인증서를 생성하고 API를 사용하여 업로드합니다. 각 S/MIME 인증서는 사용자 이메일 계정의 특정 별칭에 해당합니다. 별칭에는 기본 이메일 주소와 맞춤 '다른 주소에서 메일 보내기' 주소가 포함됩니다. 단일 S/MIME 인증서가 각 별칭의 기본값으로 표시됩니다.\nAPI 액세스 승인", '/* Class to demonstrate the use of Gmail Insert Certificate from CSV File */\npublic class InsertCertFromCsv {\n  /**\n   * Upload S/MIME certificates based on the contents of a CSV file.\n   *\n   * <p>Each row of the CSV file should contain a user ID, path to the certificate, and the\n   * certificate password.\n   *\n   * @param csvFilename Name of the CSV file.\n   */\n  public static void insertCertFromCsv(String csvFilename) {\n    try {\n      File csvFile = new File(csvFilename);\n      CSVParser parser =\n          CSVParser.parse(csvFile, java.nio.charset.StandardCharsets.UTF_8, CSVFormat.DEFAULT);\n      for (CSVRecord record : parser) {\n        String userId = record.get(0);\n        String certFilename = record.get(1);\n        String certPassword = record.get(2);\n        SmimeInfo smimeInfo = CreateSmimeInfo.createSmimeInfo(certFilename,\n            certPassword);\n        if (smimeInfo != null) {\n          InsertSmimeInfo.insertSmimeInfo(userId,\n              userId,\n              smimeInfo);\n        } else {\n          System.err.printf("Unable to read certificate file for userId: %s\\n", userId);\n        }\n      }\n    } catch (Exception e) {', 'if not send_as_email:\n      send_as_email = user_id\n\n    # pylint: disable=maybe-no-member\n    results = (\n        service.users()\n        .settings()\n        .sendAs()\n        .smimeInfo()\n        .insert(userId=user_id, sendAsEmail=send_as_email, body=smime_info)\n        .execute()\n    )\n    print(f\'Inserted certificate; id: {results["id"]}\')\n\n  except HttpError as error:\n    print(f"An error occurred: {error}")\n    results = None\n\n  return results\n\n\nif __name__ == "__main__":\n  insert_smime_info()\n여러 사용자의 인증서 관리 예\n조직의 여러 사용자에 대한 인증서를 한 번에 관리해야 할 수 있습니다. 다음 예에서는 일괄 호출 하나로 여러 사용자의 인증서를 관리하는 방법을 보여줍니다.\nCSV 파일에서 인증서 삽입\n사용자 ID와 각 사용자의 인증서 경로가 나열된 CSV 파일이 있다고 가정해 보겠습니다.\n$ cat certificates.csv\nuser1@example.com,/path/to/user1_cert.p12,cert_password_1\nuser2@example.com,/path/to/user2_cert.p12,cert_password_2\nuser3@example.com,/path/to/user3_cert.p12,cert_password_3\n--- 탭: 자바 ---\n이전의 createSmimeInfo 및 insertSmimeInfo 호출을 사용하여 CSV 파일에 지정된 인증서를 업로드할 수 있습니다.', '특정 키로 서명된 S/MIME 메일을 수신할 때 Gmail에서는 연결된 사용자에게 전송되는 메일을 암호화할 때 가장 먼 미래의 not_before 유효 기간을 기본값으로 사용하여 키를 연결합니다. 사용자가 이미 소통한 Gmail 사용자가 새 기본 키를 사용하도록 하려면 새 기본 키의 not_before 날짜가 이전 기본 키보다 늦거나 이전 기본 키를 취소해야 합니다.\n샘플 코드\n다음 코드 샘플은 API를 사용하여 사용자가 여러 명인 조직의 S/MIME 인증서를 관리하는 방법을 보여줍니다.\nS/MIME 인증서의 SmimeInfo 리소스 만들기\n다음 코드 샘플은 파일에서 인증서를 읽고, base64url 문자열로 인코딩하고, smimeInfo 리소스의 pkcs12 필드에 할당하는 방법을 보여줍니다.\n--- 탭: 자바 ---\n.filepath {\n    color: #fff;\n    margin: 6px;\n    max-width: calc(100% - 160px); /* Give at least 160px for the "View on GitHub" button. */\n    text-overflow: ellipsis;\n    text-shadow: rgba(0,0,0,0.1) 1px 1px;\n    overflow: hidden;\n  }\n  .github-docwidget-gitinclude-code .prettyprint {\n    margin: 0;\n  }\n  .view-on-github {\n    text-shadow: rgba(12,12,12,0.1) 1px 1px;\n  }\n\n\n\n  \n  gmail/snippets/src/main/java/CreateSmimeInfo.java\n  \n    \n    GitHub에서 보기 [https://github.com/googleworkspace/java-samples/blob/main/gmail/snippets/src/main/java/CreateSmimeInfo.java]\n  \n  \n  \n\n  \n    \n  \n  \n  import com.google.api.services.gmail.model.SmimeInfo;\nimport java.io.File;\nimport java.io.FileInputStream;\nimport java.io.IOException;\nimport java.io.InputStream;\nimport java.util.Base64;', 'Args:\n    csv_filename: Name of the CSV file.\n  """\n\n  try:\n    with open(csv_filename, "rb") as cert:\n      csv_reader = csv.reader(cert, delimiter=",")\n      next(csv_reader, None)  # skip CSV file header\n      for row in csv_reader:\n        user_id = row[0]\n        cert_filename = row[1]\n        cert_password = row[2]\n        smime_info = create_smime_info.create_smime_info(\n            cert_filename=cert_filename, cert_password=cert_password\n        )\n        if smime_info:\n          insert_smime_info.insert_smime_info()\n        else:\n          print(f"Unable to read certificate file for user_id: {user_id}")\n        return smime_info\n\n  except (OSError, IOError) as error:\n    print(f"An error occured while reading the CSV file: {error}")', 'from datetime import datetime\n\nimport create_smime_info\nimport google.auth\nimport insert_smime_info\nfrom googleapiclient.discovery import build\nfrom googleapiclient.errors import HttpError\n\n\ndef update_smime_cert(\n    user_id, send_as_email, cert_filename, cert_password, expire_dt\n):\n  """Update S/MIME certificates for the user.\n\n  First performs a lookup of all certificates for a user.  If there are no\n  certificates, or they all expire before the specified date/time, uploads the\n  certificate in the specified file.  If the default certificate is expired or\n  there was no default set, chooses the certificate with the expiration furthest\n  into the future and sets it as default.\n\n  Args:\n    user_id: User\'s email address.\n    send_as_email: The "send as" email address, or None if it should be the same\n        as user_id.\n    cert_filename: Name of the file containing the S/MIME certificate.\n    cert_password: Password for the certificate file, or None if the file is not\n        password-protected.\n    expire_dt: DateTime object against which the certificate expiration is\n      compared.  If None, uses the current time.', "API 액세스 승인\nAPI에 대한 액세스 권한을 부여하는 방법에는 두 가지가 있습니다.\n도메인 전체 권한 위임이 있는 서비스 계정을 사용할 수 있습니다. 이러한 용어에 대한 설명은 인증 및 승인 개요 용어 [https://developers.google.com/workspace/guides/auth-overview?hl=ko#terms]를 참고하세요. 이 옵션을 사용 설정하는 방법은 도메인 전체 권한 위임으로 서비스 계정 만들기 [https://developers.google.com/workspace/guides/create-credentials?hl=ko#createsvc]를 참고하세요.\n최종 사용자 동의가 필요한 표준 OAuth2 흐름을 사용하여 OAuth2 액세스 토큰을 획득할 수 있습니다. 자세한 내용은 인증 및 승인 개요 [https://developers.google.com/workspace/guides/auth-overview?hl=ko]를 참고하세요. 이 옵션을 사용하려면 도메인 관리자가 도메인 제어판에서 'S/MIME API 최종 사용자 액세스 사용 설정' 체크박스를 사용 설정해야 합니다.\nACL 범위\n이 API는 Gmail sendAs [https://developers.google.com/workspace/gmail/api/v1/reference/users/settings/sendAs?hl=ko] 메서드와 동일한 ACL 범위 [https://developers.google.com/workspace/gmail/api/auth/scopes?hl=ko]를 사용합니다.\ngmail.settings.basic\n이 범위는 기본 '보낸 사람' S/MIME를 업데이트하는 데 필요합니다.\ngmail.settings.sharing\n이 범위는 맞춤 from S/MIME를 업데이트하는 데 필요합니다.\nAPI 사용\nusers.settings.sendAs.smimeInfo [https://developers.google.com/workspace/gmail/api/v1/reference/users/settings/sendAs/smimeInfo?hl=ko] 리소스는 S/MIME 인증서를 관리하는 데 사용하는 메서드를 제공합니다. 각 인증서는 사용자의 하나의 보내기 권한 별칭과 연결됩니다.", "userId\n사용자의 이메일 주소입니다. 특수 값 me를 사용하여 현재 인증된 사용자를 나타낼 수 있습니다.\nsendAsEmail\n키를 나열할 별칭입니다. 이 별칭을 사용하여 보낸 메일의 '보낸사람' 헤더에 표시되는 이메일 주소입니다.\n키는 pem 형식으로만 반환되며 비공개 키가 아닌 S/MIME 인증서만 포함합니다.\n별칭의 S/MIME 키 가져오기\nsmimeInfo.get() [https://developers.google.com/workspace/gmail/api/v1/reference/users/settings/sendAs/smimeInfo/get?hl=ko] 메서드를 사용하여 사용자의 특정 전송 별칭에 대한 특정 S/MIME 키를 반환합니다. 다음 매개변수를 사용하여 타겟 별칭을 식별합니다.\nuserId\n사용자의 이메일 주소입니다. 특수 값 me를 사용하여 현재 인증된 사용자를 나타낼 수 있습니다.\nsendAsEmail\n키를 가져올 별칭입니다. 이 별칭을 사용하여 보낸 메일의 '보낸사람' 헤더에 표시되는 이메일 주소입니다.\n키는 pem 형식으로만 반환되며 비공개 키가 아닌 S/MIME 인증서만 포함합니다.\nS/MIME 키 삭제\nsmimeInfo.delete() [https://developers.google.com/workspace/gmail/api/v1/reference/users/settings/sendAs/smimeInfo/delete?hl=ko] 메서드를 사용하여 별칭에서 지정된 S/MIME 키를 삭제합니다. 다음 매개변수를 사용하여 타겟 별칭을 식별합니다.\nuserId\n사용자의 이메일 주소입니다. 특수 값 me를 사용하여 현재 인증된 사용자를 나타낼 수 있습니다.\nsendAsEmail\n키를 가져올 별칭입니다. 이 별칭을 사용하여 보낸 메일의 '보낸사람:' 헤더에 표시되는 이메일 주소입니다.\nid\nSmimeInfo의 변경 불가능한 ID입니다.\n삭제된 키는 더 이상 표시되거나 사용할 수 없으며 해당 공개 키를 사용하여 암호화된 S/MIME 이메일은 복호화할 수 없습니다. 따라서 키를 삭제하기 전에 발급 기관 (CA)을 사용하여 키를 취소하는 것이 좋습니다.\n별칭의 기본 S/MIME 키 설정", '/* Class to demonstrate the use of Gmail Update Smime Certificate API*/\npublic class UpdateSmimeCerts {\n  /**\n   * Update S/MIME certificates for the user.\n   *\n   * <p>First performs a lookup of all certificates for a user. If there are no certificates, or\n   * they all expire before the specified date/time, uploads the certificate in the specified file.\n   * If the default certificate is expired or there was no default set, chooses the certificate with\n   * the expiration furthest into the future and sets it as default.\n   *\n   * @param userId       User\'s email address.\n   * @param sendAsEmail  The "send as" email address, or None if it should be the same as user_id.\n   * @param certFilename Name of the file containing the S/MIME certificate.\n   * @param certPassword Password for the certificate file, or None if the file is not\n   *                     password-protected.\n   * @param expireTime   DateTime object against which the certificate expiration is compared. If\n   *                     None, uses the current time. @ returns: The ID of the default certificate.\n   * @return The ID of the default certificate, {@code null} otherwise.', 'import base64\n\n\ndef create_smime_info(cert_filename, cert_password):\n  """Create an smimeInfo resource for a certificate from file.\n  Args:\n    cert_filename: Name of the file containing the S/MIME certificate.\n    cert_password: Password for the certificate file, or None if the file is not\n        password-protected.\n  Returns : Smime object, including smime information\n  """\n\n  smime_info = None\n  try:\n    with open(cert_filename, "rb") as cert:\n      smime_info = {}\n      data = cert.read().encode("UTF-8")\n      smime_info["pkcs12"] = base64.urlsafe_b64encode(data).decode()\n      if cert_password and len(cert_password) > 0:\n        smime_info["encryptedKeyPassword"] = cert_password\n\n  except (OSError, IOError) as error:\n    print(f"An error occurred while reading the certificate file: {error}")\n    smime_info = None\n\n  return smime_info', 'def get_authorization_url(email_address, state):\n  """Retrieve the authorization URL.\n\n  Args:\n    email_address: User\'s e-mail address.\n    state: State for the authorization URL.\n\n  Returns:\n    Authorization URL to redirect the user to.\n  """\n  flow = flow_from_clientsecrets(CLIENTSECRETS_LOCATION, \' \'.join(SCOPES))\n  flow.params[\'access_type\'] = \'offline\'\n  flow.params[\'approval_prompt\'] = \'force\'\n  flow.params[\'user_id\'] = email_address\n  flow.params[\'state\'] = state\n  # The step1_get_authorize_url method uses the flow.redirect_uri attribute.\n  flow.redirect_uri = REDIRECT_URI\n  return flow.step1_get_authorize_url()\n\ndef get_credentials(authorization_code, state):\n  """Retrieve credentials using the provided authorization code.\n\n  This function exchanges the authorization code for an access token and queries\n  the UserInfo API to retrieve the user\'s e-mail address.\n\n  If a refresh token has been retrieved along with an access token, it is stored\n  in the application database using the user\'s e-mail address as key.', '// Optionally, include the following PromotionCard properties:\n      <meta itemprop="headline" content="HEADLINE2"/>\n      <meta itemprop="price" content="PRICE2"/>\n      <meta itemprop="priceCurrency" content="PRICE_CURRENCY2"/>\n      <meta itemprop="discountValue" content="DISCOUNT_VALUE2"/>\n      <meta itemprop="position" content="POSITION"/>\n    </div>\n\n    // To include more image previews, add additional PromotionCard objects.\n    // You can include up to 10 image previews in a product carousel.\n  </head>', 'with open(attachment_filename, "rb") as fp:\n      attachment_data = fp.read()\n    mime_message.add_attachment(attachment_data, maintype, subtype)\n\n    encoded_message = base64.urlsafe_b64encode(mime_message.as_bytes()).decode()\n\n    create_draft_request_body = {"message": {"raw": encoded_message}}\n    # pylint: disable=E1101\n    draft = (\n        service.users()\n        .drafts()\n        .create(userId="me", body=create_draft_request_body)\n        .execute()\n    )\n    print(f\'Draft id: {draft["id"]}\\nDraft message: {draft["message"]}\')\n  except HttpError as error:\n    print(f"An error occurred: {error}")\n    draft = None\n  return draft\n\n\ndef build_file_part(file):\n  """Creates a MIME part for a file.\n\n  Args:\n    file: The path to the file to be attached.\n\n  Returns:\n    A MIME part that can be attached to a message.\n  """\n  content_type, encoding = mimetypes.guess_type(file)']
[basic_langgraph_node] 생성된 답변: CSV 파일을 이용해서 S/MIME 인증서를 관리하려면 다음과 같은 작업이 필요합니다:

1. **CSV 파일 준비**: CSV 파일에는 각 행에 사용자 ID, 인증서 경로, 인증서 비밀번호가 포함되어야 합니다. 예를 들어:
   ```
   user1@example.com,/path/to/user1_cert.p12,cert_password_1
   user2@example.com,/path/to/user2_cert.p12,cert_password_2
   user3@example.com,/path/to/user3_cert.p12,cert_password_3
   ```

2. **CSV 파일 처리 함수 작성**: CSV 파일을 읽고 각 행의 정보를 사용하여 S/MIME 인증서를 업로드하는 함수를 작성합니다. Python에서는 `insert_cert_from_csv` 함수를 사용할 수 있습니다. 이 함수는 CSV 파일을 열고 각 행을 읽어 사용자 ID, 인증서 경로, 인증서 비밀번호를 추출합니다. 그런 다음 `create_smime_info`와 `insert_smime_info` 함수를 사용하여 인증서를 업로드합니다.

3. **인증서 업로드 및 기본값 설정**: 업로드된 인증서 중 만료일이 가장 늦은 인증서를 기본값으로 설정합니다. 기본 인증서가 만료되었거나 설정되지 않은 경우, 지정된 파일에서 인증서를 업로드하고 기본값으로 설정합니다.

이러한 작업을 통해 여러 사용자의 S/MIME 인증서를 효율적으로 관리할 수 있습니다.
[evaluate_answer_node] 평가 결과: good
[evaluate_answer_node] 최종 : good

In [17]:
### RAGAS 평가 실행

# LLM 래퍼 생성
evaluator_llm = ChatOpenAI(model="gpt-4.1-mini", temperature=0)
evaluator_llm = LangchainLLMWrapper(evaluator_llm)

# 평가 메트릭 정의
metrics = [
    LLMContextRecall(),  # 검색된 컨텍스트의 회수율
    Faithfulness(),  # 생성된 답변의 충실도
    FactualCorrectness()  # 사실적 정확성
]
# 평가 실행

result = evaluate(
    dataset=ragas_evaluated_dataset,
    metrics=metrics,
    llm=evaluator_llm,
)

print(result)
# 결과를 DataFrame으로 변환
result_df = result.to_pandas()

# 결과 저장
# result_df.to_csv('ragas_evaluation_result_hybrid4.csv', index=False)

display(result_df.head())
result_df[['context_recall', 'faithfulness', 'factual_correctness(mode=f1)']].describe()

Evaluating:   0%|          | 0/60 [00:00<?, ?it/s]

{'context_recall': 0.9250, 'faithfulness': 0.8906, 'factual_correctness(mode=f1)': 0.5415}

,user_input,retrieved_contexts,response,reference,context_recall,faithfulness,factual_correctness(mode=f1)
0,CSV 파일을 이용해서 S/MIME 인증서를 관리하려면 어떤 작업이 필요한가요?,"[except (OSError, IOError) as error:\n prin...",CSV 파일을 이용해서 S/MIME 인증서를 관리하려면 다음과 같은 작업이 필요합니...,"CSV 파일을 처리하는 함수에서는 사용자의 인증서를 나열하고, 기본 인증서가 만료되...",1.0,1.000000,0.42
1,클라우드 파이어스토어 부하 분산기 어떻게 써야되나요?,[Cloud Firestore의 분할은 필요할 때 또는 키 공간이 확장될 때 더 많...,Cloud Firestore는 데이터베이스에 대한 트래픽을 지원하기 위해 자동으로 ...,Cloud Firestore는 데이터베이스에 대한 트래픽을 지원하기 위해 자동으로 ...,1.0,1.000000,0.60
2,범위 많으면 동의 어렵나요?,[Cloud Firestore의 분할은 필요할 때 또는 키 공간이 확장될 때 더 많...,"""(범위가 많으면 동의가 어려운지)""는 제가 모르는 내용입니다. 일상 질문 혹은 구...",요청된 범위 수가 많으면 사용자 동의를 얻을 가능성이 낮아질 수 있습니다.,0.0,0.000000,0.00
3,As a beginner who is not familiar with Google ...,[또한 사용자 계정 또는 서비스 계정이 모든 클라이언트에서 보유할 수 있는 총 새로...,When Google Cloud session control features are...,When Google Cloud session control features are...,1.0,1.000000,0.67
4,"firebase_functions 어떻게 쓰는지 잘 모르겠는데, Cloud Fire...",[Cloud Functions로 Firestore 확장\n\nbookmark_bor...,Cloud Firestore에서 문서가 변경될 때마다 자동으로 실행되는 함수를 작성...,Cloud Firestore에서 특정 문서의 모든 변경에 이벤트를 트리거하려면 on...,1.0,0.894737,0.58

       context_recall  faithfulness  factual_correctness(mode=f1)
count        20.00000     20.000000                     20.000000
mean          0.92500      0.890570                      0.541500
std           0.24468      0.250809                      0.277285
min           0.00000      0.000000                      0.000000
25%           1.00000      0.973684                      0.395000
50%           1.00000      1.000000                      0.590000
75%           1.00000      1.000000                      0.670000
max           1.00000      1.000000                      1.000000

In [18]:
display(result_df)

,user_input,retrieved_contexts,response,reference,context_recall,faithfulness,factual_correctness(mode=f1)
0,CSV 파일을 이용해서 S/MIME 인증서를 관리하려면 어떤 작업이 필요한가요?,"[except (OSError, IOError) as error:\n prin...",CSV 파일을 이용해서 S/MIME 인증서를 관리하려면 다음과 같은 작업이 필요합니...,"CSV 파일을 처리하는 함수에서는 사용자의 인증서를 나열하고, 기본 인증서가 만료되...",1.0,1.000000,0.42
1,클라우드 파이어스토어 부하 분산기 어떻게 써야되나요?,[Cloud Firestore의 분할은 필요할 때 또는 키 공간이 확장될 때 더 많...,Cloud Firestore는 데이터베이스에 대한 트래픽을 지원하기 위해 자동으로 ...,Cloud Firestore는 데이터베이스에 대한 트래픽을 지원하기 위해 자동으로 ...,1.0,1.000000,0.60
2,범위 많으면 동의 어렵나요?,[Cloud Firestore의 분할은 필요할 때 또는 키 공간이 확장될 때 더 많...,"""(범위가 많으면 동의가 어려운지)""는 제가 모르는 내용입니다. 일상 질문 혹은 구...",요청된 범위 수가 많으면 사용자 동의를 얻을 가능성이 낮아질 수 있습니다.,0.0,0.000000,0.00
3,As a beginner who is not familiar with Google ...,[또한 사용자 계정 또는 서비스 계정이 모든 클라이언트에서 보유할 수 있는 총 새로...,When Google Cloud session control features are...,When Google Cloud session control features are...,1.0,1.000000,0.67
4,"firebase_functions 어떻게 쓰는지 잘 모르겠는데, Cloud Fire...",[Cloud Functions로 Firestore 확장\n\nbookmark_bor...,Cloud Firestore에서 문서가 변경될 때마다 자동으로 실행되는 함수를 작성...,Cloud Firestore에서 특정 문서의 모든 변경에 이벤트를 트리거하려면 on...,1.0,0.894737,0.58
5,Firebase에서 다단계 인증(MFA)을 사용할 때 Objective-C로 사용자...,[Firebase Authentication with Identity Platfor...,Objective-C에서 Firebase 다단계 인증(MFA) 사용자를 인증하는 방...,다단계 인증(MFA) 사용 시 Firebase에서 사용자 인증을 완료하는 방법은 F...,1.0,1.000000,0.64
6,Java를 사용해서 Firestore에 문서를 추가할 때 어떤 코드를 사용하나요?,[Firestore는 컬렉션에 저장되는 문서에 데이터를 저장합니다.\n문서에 데이터...,Java를 사용하여 Firestore에 문서를 추가하는 방법은 다음과 같습니다. 아...,다음은 Java에서 Firestore에 문서를 추가할 때 사용하는 코드 예시입니다....,0.5,1.000000,0.17
7,COLUMNS가 Dimension API에서 무슨 뜻인가요?,[COLUMN_NAME: 임베딩 데이터가 포함된 열의 이름입니다. 이 열은 ARRA...,"Dimension API에서 ""COLUMNS""는 시트의 열에서 작동하는 것을 의미합...",COLUMNS는 Dimension API에서 시트의 열에서 작동함을 의미합니다.,1.0,1.000000,1.00
8,ttll이 뭐에요? 그리고 한도 같은거 있나요?,[TtlConfig\n\nThe TTL (time-to-live) configura...,TTL(Time-to-Live)은 문서의 수명을 설정하는 구성입니다. TTL이 활성...,"컬렉션 그룹당 하나의 필드만 TTL 필드로 표시할 수 있고, 필드 수준 구성은 최대...",1.0,1.000000,0.55
9,Me want know what FUNCTION_ENTRYPOINT do in gc...,[--- 탭: gcloud [https://cloud.google.com/fires...,"In the `gcloud run deploy` command, the `FUNCT...",FUNCTION_ENTRYPOINT는 gcloud run deploy 명령어에서 함...,1.0,0.500000,0.40
10,Google 피트니스 심박수 데이터 읽기 권한 범위는?,[https://www.googleapis.com/auth/fitness.body_...,Google 피트니스에서 심박수 데이터를 읽기 위해 필요한 OAuth 2.0 범위는...,Google 피트니스에서 심박수 데이터를 확인하기 위해 필요한 OAuth 2.0 범...,1.0,1.000000,1.00
11,projets.databeses.gte 메서드 쓸때 HTTP 리퀘스트 포맷이 뭐에요?,[Gets multiple documents.Documents returned by...,"죄송하지만, ""projets.databeses.gte"" 메서드에 대한 정보는 제공된...",HTTP 요청 형식은 다음과 같습니다:\r\n```\r\nGET https://fi...,1.0,0.666667,0.57
12,Google Developers Console을 활용하여 YouTube Data A...,[YouTube에서 Shorts 동영상의 조회수를 집계하는 방식에 맞게 Data A...,YouTube Data API를 사용 설정하기 위해 Google Developers...,YouTube Data API를 사용 설정하기 위한 첫 번째 단계는 Google D...,1.0,1.000000,0.67
13,firsetore users 데이타 가져오려면 어떻게하나요? users 콜렉션에서 ...,[users_ref = firestore.col collection_path\nus...,Firestore에서 `users` 컬렉션의 모든 사용자 데이터를 가져오려면 `ge...,Firestore에서 users 콜렉션의 모든 users 정보를 가져오려면 다음과 ...,1.0,1.000000,0.38
14,Python에서 Cloud Firestore 초기화 방법,[참고: 코드 샘플에서는 여러 언어를 다루지만 샘플을 설명하는 텍스트는 웹 메서드 ...,Python에서 Cloud Firestore를 초기화하는 방법은 다음과 같습니다:\...,Cloud Firestore를 Python에서 서비스 계정을 사용하여 초기화하려면 ...,1.0,1.000000,0.67
15,"BigQuery에서 쿼리 실행 단계의 병렬 입력 세그먼트 수를 확인하고자 할 때, ...",[입력: 표에서 데이터를 읽거나 특정 열을 선택\n조인: JOIN 조건을 기반으로 ...,BigQuery에서 쿼리 실행 단계의 병렬 입력 세그먼트 수를 확인하려면 'para...,BigQuery에서 쿼리 실행 단계의 병렬 입력 세그먼트 수를 확인하려면 'para...,1.0,0.750000,0.75
16,itemDownlodRestrction 뭐에요?,[inheritedPermissionsDisabled\nboolean\n이 파일에 ...,'itemDownloadRestriction'은 파일의 다운로드 제한사항을 확인하는...,itemDownloadRestriction 필드는 소유자 또는 주최자가 직접 적용한...,1.0,1.000000,0.67
17,What does the textFormat field represent in Tr...,[스코어카드 차트의 숫자 키/기준 값에 대한 맞춤 형식 지정 옵션입니다. 이 필드는...,The `textFormat` field in the JSON representat...,The textFormat field specifies the text format...,1.0,1.000000,0.80
18,fileId는 무엇을 의미하나요?,[| Fields |\n| --- |\n| target_id | int32 The ...,'fileId'는 Google Drive API에서 파일의 고유 식별자를 의미합니다...,fileId는 파일의 ID를 의미합니다.,1.0,1.000000,0.29
19,"Gmail 작업을 선언하는 방법에 대해 자세히 알고 싶은데, Declaring Ac...",[Gmail 작업\nGmail은 schema.org 마크업을 사용하여 사용자 작업을...,"Gmail 작업을 선언하는 방법에 대한 자세한 내용은 ""작업 선언(Declaring...",작업 선언 방법에 대한 자세한 내용은 작업 선언(Declaring Actions) ...,1.0,1.000000,0.00