### 원문 벡터 db + QA 벡터 DB -> 답변 평가 후 -> HyDE 재실행
```
extract_queries → split_queries → tool → qa_tool → basic 
→ evaluate ── good → END
            └─ bad → hyde → tool → qa_tool → basic → evaluate → END
```

In [1]:
from pathlib import Path
import sys

root = Path.cwd()
while not (root / "utils_v9").exists() and root != root.parent:
    root = root.parent
sys.path.insert(0, str(root))

from utils_v9.main3 import (run_langraph)

C:\Users\playdata\Documents\1_ai\LLM_hybrid\utils_v9\retriever.py:51: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-chroma package and should be used instead. To use it run `pip install -U :class:`~langchain-chroma` and import as `from :class:`~langchain_chroma import Chroma``.
  vs = Chroma(

In [2]:
from utils_v9.langgraph_setting2 import graph_setting

graph = graph_setting()

graph

ValueError: Failed to reach https://mermaid.ink/ API while trying to render your graph. Status code: 502.

To resolve this issue:
1. Check your internet connection and try again
2. Try with higher retry settings: `draw_mermaid_png(..., max_retries=5, retry_delay=2.0)`
3. Use the Pyppeteer rendering method which will render your graph locally in a browser: `draw_mermaid_png(..., draw_method=MermaidDrawMethod.PYPPETEER)`

In [3]:
response = run_langraph('Firebase의 updateTime 필드에 사용되는 시간 형식이 뭐야?', '1', None)

run_langraph 호출 - 입력: Firebase의 updateTime 필드에 사용되는 시간 형식이 뭐야?, 이미지: False
analyze_image 호출됨 - 이미지 존재: False
[tool_based_search_node] 실행 - queries=['Firebase의 updateTime 필드에 사용되는 시간 형식은 무엇인가요?', 'What is the time format used in the updateTime field of Firebase?']
원문 retriever 생성 완료
QA retriever 생성 완료

C:\Users\playdata\Documents\1_ai\LLM_hybrid\utils_v9\langgraph_node2.py:201: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use :meth:`~invoke` instead.
  results_text = retriever.get_relevant_documents(query)

원문 검색 결과: 길이 14개, 첫 문서: | Fields |
| --- |
| name | string The resource name of the Database. Format: projects/{project}/dat
QA 검색 결과: 길이 23개, 첫 문서: Q: Firestore 문서의 생성 시간(createTime)과 업데이트 시간(updateTime)의 형식은 어떻게 되나요?
A: 두 시간 모두 RFC 3339 형식을 사용하며,
[vector_search_tool] hybrid 검색 완료: 'Firebase의 updateTime 필드에 사용되는 시간 형식은 무엇인가요?', tags=['firestore']
원문 retriever 생성 완료
QA retriever 생성 완료
원문 검색 결과: 길이 13개, 첫 문서: | Fields |
| --- |
| name | string The resource name of the Database. Format: projects/{project}/dat
QA 검색 결과: 길이 24개, 첫 문서: Q: Cloud Firestore 데이터베이스의 업데이트 시간을 확인하는 방법은 무엇인가요?
A: 데이터베이스의 업데이트 시간은 `updateTime` 필드에서 확인할 수 있습니다
[vector_search_tool] hybrid 검색 완료: 'What is the time format used in the updateTime field of Firebase?', tags=['firestore']

In [4]:
print(response['answer'])

Firebase의 `updateTime` 필드는 RFC 3339 형식을 사용합니다. 이 형식은 항상 Z-normalized되며 0, 3, 6 또는 9의 소수 자릿수를 사용할 수 있습니다. 예시로는 "2014-10-02T15:01:23Z", "2014-10-02T15:01:23.045123456Z" 또는 "2014-10-02T15:01:23+05:30"가 있습니다.

In [5]:
response = run_langraph('GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?', '1', None)
print(response)

run_langraph 호출 - 입력: GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?, 이미지: False
analyze_image 호출됨 - 이미지 존재: False
[tool_based_search_node] 실행 - queries=['GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?', 'What does the point (0, 0) represent in the GMSMapPoint coordinate system?']
원문 retriever 생성 완료
QA retriever 생성 완료
원문 검색 결과: 길이 16개, 첫 문서: GMSProjection [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Cl
QA 검색 결과: 길이 25개, 첫 문서: Q: GMSProjection 클래스는 어떤 기능을 제공하나요?
A: GMSProjection 클래스는 지구 좌표 CLLocationCoordinate2D와 맵 뷰의 좌표 CGPo
[vector_search_tool] hybrid 검색 완료: 'GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?', tags=['map']
원문 retriever 생성 완료
QA retriever 생성 완료
원문 검색 결과: 길이 16개, 첫 문서: GMSProjection [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Cl
QA 검색 결과: 길이 25개, 첫 문서: Q: GMSProjection 클래스는 어떤 기능을 제공하나요?
A: GMSProjection 클래스는 지구 좌표 CLLocationCoordinate2D와 맵 뷰의 좌표 CGPo
[vector_search_tool] hybrid 검색 완료: 'What does the point (0, 0) represent in the GMSMapPoint coordinate system?', tags=['map']

In [6]:
print(response['answer'])
# # print(response['tool_calls'])
# print(response['qa_tool_calls'])

GMSMapPoint의 좌표계에서 (0, 0)은 Google 지도에서 메르카토르 투영의 원점, 즉 경도 180도와 위도 약 85도에 있는 지도의 북서쪽 모서리를 의미합니다. 이 지점에서 x 방향으로 동쪽(오른쪽)으로 증가하고, y 방향으로 남쪽(아래쪽)으로 증가합니다.

In [7]:
response = run_langraph('MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일에 직접해야 하나요?', '1', None)

run_langraph 호출 - 입력: MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일에 직접해야 하나요?, 이미지: False
analyze_image 호출됨 - 이미지 존재: False
[tool_based_search_node] 실행 - queries=['MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일을 직접 수정해야 하나요?', 'Do I need to directly modify the config.json file to configure the cover of MAP 3D storytelling?']
원문 retriever 생성 완료
QA retriever 생성 완료
원문 검색 결과: 길이 16개, 첫 문서: downloadJSON 스키마 다운로드 [https://developers.google.com/static/maps/cbms-json-schema.json?hl=ko]
스타일 편집
QA 검색 결과: 길이 22개, 첫 문서: Q: JSON 스타일 지정을 사용하여 지도를 수동으로 맞춤설정하는 방법은 무엇인가요?
A: 지도를 수동으로 맞춤설정하면 일반 지도 유형의 스타일을 지정할 수 있으며 지도 ID가 필
[vector_search_tool] hybrid 검색 완료: 'MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일을 직접 수정해야 하나요?', tags=['map']
원문 retriever 생성 완료
QA retriever 생성 완료
원문 검색 결과: 길이 16개, 첫 문서: assignment [https://developers.google.com/maps/architecture/3d-storytelling-customizations?hl=ko]
맞춤
QA 검색 결과: 길이 23개, 첫 문서: Q: JSON 스타일 지정을 사용하여 지도를 수동으로 맞춤설정하는 방법은 무엇인가요?
A: 지도를 수동으로 맞춤설정하면 일반 지도 유형의 스타일을 지정할 수 있으며 지도 ID가 필
[vector_search_tool] hybrid 검색 완료: 'Do I need to directly modify the config.json file to configure the cover of MAP 3D storytelling?', tags=['map']

In [8]:
print(response['answer'])

죄송하지만, 제공된 문서에는 "MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일에 직접해야 하는지"에 대한 정보가 포함되어 있지 않습니다. 따라서 이 질문에 대한 답변을 제공할 수 없습니다. 다른 질문이 있으시면 말씀해 주세요.

In [9]:
## 환경설정
# !pip install -qU ragas langchain langchain-community langchain-openai langchain-chroma langchain-text-splitters pypdf rapidfuzz langgraph gdown chromadb langchain-huggingface sentence-transformers -q

In [7]:
# !pip install ragas

In [3]:
import os
from dotenv import load_dotenv

load_dotenv()
# 필요한 라이브러리 임포트
import os
import pandas as pd
from pprint import pprint
# LangChain 관련 라이브러리
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
# RAGAS 관련 라이브러리
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.testset.persona import Persona
from ragas.testset import TestsetGenerator
from ragas import EvaluationDataset, evaluate
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness

## 이미 생성된 합성 데이터셋 생성

In [4]:
import pandas as pd

# 같은 폴더(현재 작업 디렉토리)에 저장했다면
dataset_df = pd.read_csv("./dataset.csv")
print(dataset_df.shape)
display(dataset_df)

(20, 3)

,user_input,reference_contexts,reference
0,Analytics Hub 게시자와 목록 관리자 역할의 차이점은 무엇인가요?,사용자가 다음 작업을 수행할 수 있게 해주는 Analytics Hub 게시자 역할(...,"Analytics Hub 게시자 역할은 목록을 생성, 업데이트, 삭제하고 목록에 I..."
1,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 어떻게 해...,BigQuery Studio 저장된 쿼리에 공개 액세스 권한이 부여되지 않도록 하려...,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 프로젝트에...
2,calendarId에 primary 키워드를 사용하면 어떤 캘린더에 접근할 수 있나요?,현재 로그인한 사용자의 기본 캘린더에 액세스하려면 'primary' 키워드를 사용하세요.,calendarId에 primary 키워드를 사용하면 현재 로그인한 사용자의 기본 ...
3,Google Drive API v3의 서비스 엔드포인트가 궁금해,"이 서비스에는 다음 서비스 엔드포인트가 포함되고, 그 아래의 모든 URI가 이 서비...",Google Drive API v3의 서비스 엔드포인트는 https://www.go...
4,files.create 메서드의 최대 파일 크기와 허용되는 미디어 MIME 유형은 ...,"최대 파일 크기: 5,120GB\r\n허용되는 미디어 MIME 유형: */*\r\n...","files.create 메서드의 최대 파일 크기는 5,120GB입니다. 허용되는 미..."
5,Firebase scrypt 해시 비밀번호를 사용한 사용자 가져오는 방법은?,기본적으로 Firebase는 scrypt 해싱 알고리즘의 수정된 Firebase 버...,"Firebase scrypt 해시 비밀번호를 사용한 사용자를 가져오려면, 먼저 Fi..."
6,커스텀 인증 시스템으로 Firebase에 인증하려면 어떻게 해야 하나요?,Firebase 인증에 맞춤 인증 시스템을 통합할 수 있습니다. 사용자가 정상적으로...,"커스텀 인증 시스템으로 Firebase에 인증하려면, 먼저 인증 서버에서 사용자의 ..."
7,"Firestore에서 맵 필드에 대한 단일 필드 색인 예외를 설정하면, 하위 필드들...",맵 필드에 단일 필드 색인 예외를 만들면 맵의 하위 필드에서 해당 설정을 상속합니다...,"네, Firestore에서 맵 필드에 단일 필드 색인 예외를 만들면 맵의 하위 필드..."
8,Firebase의 updateTime 필드에 사용되는 시간 형식이 뭐야?,"Uses RFC 3339, where generated output will alw...",Firebase의 updateTime 필드에는 RFC 3339 시간 형식이 사용됩니...
9,Firefox 58 환경에서 Gmail의 AMP 렌더링 기능이 호환되나요?,브라우저 최소 버전\r\nChrome 69\r\nEdge 지원되지 않음\r\nFir...,"네, Firefox 58 환경에서는 Gmail의 AMP 렌더링 기능이 호환됩니다. ..."
10,Gmail 자가 테스트를 할 때 DKIM 또는 SPF 인증이 필요해?,DKIM 또는 SPF 인증 자체 테스트에는 여전히 필요합니다.,"네, Gmail 자가 테스트를 할 때 DKIM 또는 SPF 인증이 여전히 필요합니다."
11,"HTML 헤더에 스크립트 태그를 넣을 수 없을 때, 이메일 본문에 코드를 삽입하는 ...",이메일 구성 방식에 따라 이메일 본문의 할인/제품을 담당하는 시스템은 HTML 헤더...,"HTML 헤더에 스크립트 태그를 넣을 수 없는 경우, 이메일 본문에 스크립트 태그의..."
12,OAuth에서 승인 사용자 인증 정보 만드는 방법 순서대로 알려주세요.,1. 클라이언트 만들기를 클릭합니다. 2. TV 및 입력 제한 기기 애플리케이션 유...,"OAuth에서 승인 사용자 인증 정보를 만드는 방법은 다음과 같습니다. 먼저, '클..."
13,Google의 계정 간 보안 서비스를 사용하는데 디코딩된 보안 이벤트 토큰의 eve...,events 클레임에는 토큰이 나타내는 보안 이벤트에 관한 정보가 포함됩니다. 이 ...,디코딩된 보안 이벤트 토큰의 events 클레임에는 토큰이 나타내는 보안 이벤트에 ...
14,MAP 3D 스토리텔링의 '표지'를 구성하기 위해 config.json 파일에 직접...,또한 구성 파일이 있는 경우 파일에 다음 섹션을 직접 추가할 수 있습니다.\r\n\...,MAP 3D 스토리텔링의 '표지'를 구성하기 위해 config.json 파일에 직접...
15,"GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?","(0, 0) is the center of the map.","(0, 0)은 GMSMapPoint 좌표계에서 지도의 중심을 의미합니다."
16,People API의 RequestMask 필드에 무엇을 입력해야 하나요?,지원 중단된 서비스입니다.,지원 중단되었습니다. 대신 personFields를 사용해 주세요.
17,People API에 요청을 보내는 Python 스크립트를 어떻게 실행하고 구성해야...,Python용 Google 클라이언트 라이브러리를 설치합니다.\r\npip inst...,People API에 요청을 보내는 Python 스크립트를 실행하고 구성하려면 다음...
18,Google Sheets의 SERIAL_NUMBER 형식으로 1900년 2월 1일 ...,"날짜, 시간, 날짜/시간, 기간 필드를 Lotus 1-2-3에서 대중화한 '일련번호...",Google Sheets의 SERIAL_NUMBER 형식에서 1900년 2월 1일 ...
19,YouTube Data API를 사용하는 프로젝트의 기본 할당량은 얼마인가요?,"YouTube Data API를 사용 설정한 프로젝트의 기본 할당량은 일일 10,0...","YouTube Data API를 사용하는 프로젝트의 기본 할당량은 일일 10,000..."

In [5]:

## 02.RAG 체인 구성

import pandas as pd
from datasets import Dataset
import uuid
import time


evaluated_dataset = []

for _, row in dataset_df.iterrows():
    time.sleep(1)
    query = row.user_input  # 사용자 입력 - 합성 데이터셋에서 가져옴

    # run_langraph 함수 호출
    rag_result = run_langraph(query,'1', None)

    evaluated_dataset.append(
        {
            "user_input": query,
            "retrieved_contexts": [doc for doc in rag_result["search_results_final"]],
            "response": rag_result["answer"],
            "reference": row['reference']
        }
    )

print("평가 데이터셋 준비 완료")

# RAGAS 평가 데이터셋 생성
ragas_evaluated_dataset = Dataset.from_list(evaluated_dataset)
# csv 데이터 저장
# ragas_evaluated_dataset.to_pandas().to_csv('ragas_evaluated_dataset_hybrid4.csv', index=False)
ragas_evaluated_dataset.to_pandas().info()

run_langraph 호출 - 입력: Analytics Hub 게시자와 목록 관리자 역할의 차이점은 무엇인가요?, 이미지: False
analyze_image 호출됨 - 이미지 존재: False
[tool_based_search_node] 실행 - queries=['Analytics Hub에서 게시자와 목록 관리자 역할의 차이점은 무엇인가요?', 'What is the difference between the publisher and listing manager roles in Analytics Hub?']
원문 retriever 생성 완료
QA retriever 생성 완료

C:\Users\playdata\Documents\1_ai\LLM_hybrid\utils_v9\langgraph_node2.py:201: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use :meth:`~invoke` instead.
  results_text = retriever.get_relevant_documents(query)

원문 검색 결과: 길이 15개, 첫 문서: analyticshub.listings.list
소유자 [https://cloud.google.com/iam/docs/roles-overview?hl=ko#basic](roles/
QA 검색 결과: 길이 25개, 첫 문서: Q: Cloud Run 함수를 트리거하기 위해 필요한 IAM 역할은 무엇인가요?
A: 배포자 계정에 필요한 역할은 다음과 같습니다:
- Cloud Build 편집자 (roles/c
[vector_search_tool] hybrid 검색 완료: 'Analytics Hub에서 게시자와 목록 관리자 역할의 차이점은 무엇인가요?', tags=['bigquery']
원문 retriever 생성 완료
QA retriever 생성 완료
원문 검색 결과: 길이 16개, 첫 문서: 데이터 교환을 생성, 업데이트, 삭제합니다.
목록을 생성, 업데이트, 삭제, 공유
Analytics Hub 관리자, 목록 관리자, 게시자, 구독자, 뷰어를 관리합니다.
이 역할을
QA 검색 결과: 길이 25개, 첫 문서: Q: Google Maps Platform의 비즈니스 통계를 보기 위해 필요한 권한은 무엇인가요?
A: 프로젝트 소유자와 지도 애널리틱스 뷰어(roles) 역할이 있는 사용자는 C
[vector_search_tool] hybrid 검색 완료: 'What is the difference between the publisher and listing manager roles in Analytics Hub?', tags=['bigquery']

In [24]:
type(evaluated_dataset)

list

In [26]:
import pandas as pd
import time
from datasets import Dataset
from ragas import evaluate
from ragas.metrics import (
    answer_relevancy,
    faithfulness,
    context_recall,
    context_precision,
    answer_correctness,
    answer_similarity
)

# RAGAS 평가 메트릭 설정
metrics = [
    answer_relevancy,
    faithfulness,
    context_recall,
    context_precision,
    answer_correctness,
    answer_similarity
]

def evaluate_in_batches(dataset, metrics, llm, batch_size=10):
    """
    데이터셋을 배치로 나누어 RAGAS 평가를 실행하는 함수

    Args:
        dataset: 평가할 데이터셋 (dict 형태)
        metrics: RAGAS 평가 메트릭 리스트
        llm: 평가에 사용할 LLM
        batch_size: 배치 크기

    Returns:
        list: 각 배치의 평가 결과 리스트
    """

    # dict를 Dataset 객체로 변환
    if isinstance(dataset, dict):
        # 각 키의 값들이 리스트인지 확인하고 Dataset 생성
        dataset_hf = Dataset.from_dict(dataset)
    else:
        dataset_hf = dataset

    total_samples = len(dataset_hf)
    results = []

    print(f"총 {total_samples}개 샘플을 {batch_size}씩 배치로 나누어 평가합니다.")

    for i in range(0, total_samples, batch_size):
        batch_start = i
        batch_end = min(i + batch_size, total_samples)

        print(f"배치 {i//batch_size + 1}: {batch_start+1}-{batch_end} 샘플 평가 중...")

        # 현재 배치 생성
        batch_dict = {}
        for key in dataset_hf.column_names:
            batch_dict[key] = dataset_hf[key][batch_start:batch_end]

        batch_dataset = Dataset.from_dict(batch_dict)

        # 배치 처리 시간 측정 시작
        batch_start_time = time.time()

        try:
            # 배치 평가 실행
            result_batch = evaluate(
                dataset=batch_dataset,
                metrics=metrics,
                llm=llm,
            )

            # 배치 처리 시간 측정
            batch_end_time = time.time()
            batch_time = batch_end_time - batch_start_time

            print(f"배치 {i//batch_size + 1} 완료 (소요 시간: {batch_time:.2f}초)")
            results.append(result_batch)

        except Exception as e:
            print(f"배치 {i//batch_size + 1} 평가 중 오류 발생: {str(e)}")
            # 오류가 발생한 배치는 건너뛰고 계속 진행
            continue

    return results

# 사용 예시:
# ragas_evaluated_dataset가 dict 형태라면 자동으로 Dataset으로 변환됩니다
ragas_results = evaluate_in_batches(ragas_evaluated_dataset, metrics, evaluator_llm)

# 결과를 DataFrame으로 변환
if ragas_results:  # 결과가 있는 경우에만 실행
    result_df = pd.concat([result.to_pandas() for result in ragas_results], ignore_index=True)
    print(f"평가 완료! 총 {len(result_df)}개의 결과가 생성되었습니다.")
    print("\n평가 결과 요약:")
    print(result_df.describe())
else:
    print("평가 결과가 없습니다. 오류를 확인해주세요.")

총 20개 샘플을 10씩 배치로 나누어 평가합니다.
배치 1: 1-10 샘플 평가 중...

Evaluating:   0%|          | 0/60 [00:00<?, ?it/s]

Exception raised in Job[12]: IndexError(list index out of range)
Exception raised in Job[6]: IndexError(list index out of range)
Exception raised in Job[0]: IndexError(list index out of range)
Exception raised in Job[54]: IndexError(list index out of range)
Exception raised in Job[39]: TimeoutError()

배치 1 완료 (소요 시간: 201.55초)
배치 2: 11-20 샘플 평가 중...

Evaluating:   0%|          | 0/60 [00:00<?, ?it/s]

Exception raised in Job[6]: IndexError(list index out of range)
Exception raised in Job[12]: IndexError(list index out of range)
Exception raised in Job[0]: IndexError(list index out of range)
Exception raised in Job[21]: TimeoutError()
Exception raised in Job[33]: TimeoutError()
Exception raised in Job[51]: TimeoutError()

배치 2 완료 (소요 시간: 219.52초)
평가 완료! 총 20개의 결과가 생성되었습니다.

평가 결과 요약:
       answer_relevancy  faithfulness  context_recall  context_precision  \
count         13.000000     20.000000       20.000000          16.000000
mean           0.807482      0.917500        0.912500           0.660411
std            0.246808      0.150581        0.272356           0.225943
min            0.000000      0.500000        0.000000           0.219803
25%            0.839162      0.908333        1.000000           0.492686
50%            0.866376      1.000000        1.000000           0.637104
75%            0.873182      1.000000        1.000000           0.867327
max            0.956510      1.000000        1.000000           1.000000

       answer_correctness  answer_similarity
count           20.000000          20.000000
mean             0.670688           0.956888
std              0.209317           0.031761
min              0.229319           0.877996
25%              0.592596           0.941259
50%              0.683262           0.962451
75%              0.758777           0.980113
max              1.000000           1.000000

In [28]:
display(result_df)

,user_input,retrieved_contexts,response,reference,answer_relevancy,faithfulness,context_recall,context_precision,answer_correctness,answer_similarity
0,Analytics Hub 게시자와 목록 관리자 역할의 차이점은 무엇인가요?,[analyticshub.listings.list\n소유자 [https://clou...,Analytics Hub 게시자와 목록 관리자 역할의 차이점은 다음과 같습니다:\n...,"Analytics Hub 게시자 역할은 목록을 생성, 업데이트, 삭제하고 목록에 I...",NaN,0.933333,1.00,0.867741,0.743207,0.972797
1,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 어떻게 해...,[탐색기 창에서 프로젝트와 쿼리 폴더를 펼치고 필요한 경우 공유 쿼리 폴더를 펼칩니...,BigQuery Studio 저장된 쿼리에 대한 공개 액세스 권한을 방지하려면 프로...,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 프로젝트에...,NaN,1.000000,1.00,1.000000,0.794012,0.994234
2,calendarId에 primary 키워드를 사용하면 어떤 캘린더에 접근할 수 있나요?,[참고: 승인 [https://developers.google.com/workspa...,`calendarId`에 `primary` 키워드를 사용하면 현재 로그인한 사용자의...,calendarId에 primary 키워드를 사용하면 현재 로그인한 사용자의 기본 ...,NaN,1.000000,1.00,0.894156,0.742371,0.969483
3,Google Drive API v3의 서비스 엔드포인트가 궁금해,[https://www.googleapis.com/discovery/v1/apis/...,Google Drive API v3의 서비스 엔드포인트는 `https://www.g...,Google Drive API v3의 서비스 엔드포인트는 https://www.go...,0.938003,1.000000,1.00,0.556201,0.240983,0.963898
4,files.create 메서드의 최대 파일 크기와 허용되는 미디어 MIME 유형은 ...,[이 페이지는 Cloud Translation API [https://cloud.g...,files.create 메서드를 사용하여 파일을 업로드할 때 지원되는 최대 파일 크...,"files.create 메서드의 최대 파일 크기는 5,120GB입니다. 허용되는 미...",0.871723,1.000000,1.00,1.000000,0.808476,0.983904
5,Firebase scrypt 해시 비밀번호를 사용한 사용자 가져오는 방법은?,[Source URL: https://firebase.google.com/docs/...,Firebase scrypt 해시 비밀번호를 사용한 사용자를 가져오는 방법은 다음과...,"Firebase scrypt 해시 비밀번호를 사용한 사용자를 가져오려면, 먼저 Fi...",0.828419,1.000000,1.00,0.751877,0.629019,0.944691
6,커스텀 인증 시스템으로 Firebase에 인증하려면 어떻게 해야 하나요?,[Source URL: https://firebase.google.com/docs/...,Firebase에 커스텀 인증 시스템을 통합하려면 다음 단계를 따르세요:\n\n1....,"커스텀 인증 시스템으로 Firebase에 인증하려면, 먼저 인증 서버에서 사용자의 ...",0.844032,1.000000,1.00,NaN,0.607742,0.930951
7,"Firestore에서 맵 필드에 대한 단일 필드 색인 예외를 설정하면, 하위 필드들...",[맵 필드에 단일 필드 색인 예외를 만들면 맵의 하위 필드에서 해당 설정을 상속합니...,"네, Firestore에서 맵 필드에 단일 필드 색인 예외를 설정하면, 맵의 하위 ...","네, Firestore에서 맵 필드에 단일 필드 색인 예외를 만들면 맵의 하위 필드...",0.868935,1.000000,1.00,0.607846,0.747032,0.988130
8,Firebase의 updateTime 필드에 사용되는 시간 형식이 뭐야?,[| Fields |\n| --- |\n| name | string The reso...,Firebase의 `updateTime` 필드는 RFC 3339 형식을 사용합니다....,Firebase의 updateTime 필드에는 RFC 3339 시간 형식이 사용됩니...,0.866376,1.000000,1.00,0.219803,0.994712,0.978849
9,Firefox 58 환경에서 Gmail의 AMP 렌더링 기능이 호환되나요?,[Source URL: https://developers.google.com/wor...,"네, Firefox 58 환경에서는 Gmail의 AMP 렌더링 기능이 호환됩니다. ...","네, Firefox 58 환경에서는 Gmail의 AMP 렌더링 기능이 호환됩니다. ...",NaN,0.500000,1.00,0.562500,0.547160,0.988766
10,Gmail 자가 테스트를 할 때 DKIM 또는 SPF 인증이 필요해?,[이메일이 SPF (Sender Policy Framework) 인증 [https:...,"자가 테스트를 할 때, 발신자와 수신자가 동일한 계정인 모든 이메일은 등록 요구사항...","네, Gmail 자가 테스트를 할 때 DKIM 또는 SPF 인증이 여전히 필요합니다.",NaN,0.750000,1.00,0.867189,0.726917,0.907739
11,"HTML 헤더에 스크립트 태그를 넣을 수 없을 때, 이메일 본문에 코드를 삽입하는 ...",[이 페이지는 Cloud Translation API [https://cloud.g...,"HTML 헤더에 스크립트 태그를 넣을 수 없는 경우, 이메일 본문에 코드를 삽입하는...","HTML 헤더에 스크립트 태그를 넣을 수 없는 경우, 이메일 본문에 스크립트 태그의...",NaN,1.000000,1.00,0.470743,0.615251,0.961004
12,OAuth에서 승인 사용자 인증 정보 만드는 방법 순서대로 알려주세요.,[사용 설정하려는 API를 선택한 다음 사용 설정 버튼을 클릭합니다.\nIf pro...,OAuth에서 승인 사용자 인증 정보를 만드는 방법은 다음과 같습니다:\n\n1. ...,"OAuth에서 승인 사용자 인증 정보를 만드는 방법은 다음과 같습니다. 먼저, '클...",NaN,1.000000,1.00,0.732181,0.612244,0.948956
13,Google의 계정 간 보안 서비스를 사용하는데 디코딩된 보안 이벤트 토큰의 eve...,[jti 클레임은 단일 보안 이벤트를 식별하는 문자열이며 스트림에 고유합니다. 이 ...,"Google의 계정 간 보안 서비스를 사용할 때, 디코딩된 보안 이벤트 토큰의 `e...",디코딩된 보안 이벤트 토큰의 events 클레임에는 토큰이 나타내는 보안 이벤트에 ...,0.873182,1.000000,1.00,NaN,0.994043,0.976219
14,MAP 3D 스토리텔링의 '표지'를 구성하기 위해 config.json 파일에 직접...,[이 웹 애플리케이션은 3D 환경을 맞춤설정할 수 있는 사용자 친화적인 인터페이스를...,3D 스토리텔링의 '표지'를 구성하기 위해 config.json 파일에 직접 추가할...,MAP 3D 스토리텔링의 '표지'를 구성하기 위해 config.json 파일에 직접...,0.839162,0.833333,1.00,0.500000,0.686890,0.947937
15,"GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?",[GMSProjection [https://developers.google.com/...,"죄송하지만, GMSMapPoint의 좌표계에서 (0, 0)이 어떤 지점을 의미하는지...","(0, 0)은 GMSMapPoint 좌표계에서 지도의 중심을 의미합니다.",0.000000,0.666667,0.00,NaN,0.229319,0.917224
16,People API의 RequestMask 필드에 무엇을 입력해야 하나요?,[Source URL: https://developers.google.com/peo...,"People API의 RequestMask 필드는 지원 중단되었습니다. 대신, pe...",지원 중단되었습니다. 대신 personFields를 사용해 주세요.,0.816044,0.666667,1.00,0.450761,0.519494,0.877996
17,People API에 요청을 보내는 Python 스크립트를 어떻게 실행하고 구성해야...,[샘플 구성 [https://developers.google.com/people/q...,People API에 요청을 보내는 Python 스크립트를 실행하고 구성하는 방법은...,People API에 요청을 보내는 Python 스크립트를 실행하고 구성하려면 다음...,0.847573,1.000000,1.00,0.419215,0.495247,0.930963
18,Google Sheets의 SERIAL_NUMBER 형식으로 1900년 2월 1일 ...,[Source URL: https://developers.google.com/wor...,1900년 2월 1일 오후 5시의 경우 SERIAL_NUMBER 형식으로 계산하면 ...,Google Sheets의 SERIAL_NUMBER 형식에서 1900년 2월 1일 ...,0.947307,1.000000,0.25,NaN,0.679635,0.954022
19,YouTube Data API를 사용하는 프로젝트의 기본 할당량은 얼마인가요?,[YouTube에서 Shorts 동영상의 조회수를 집계하는 방식에 맞게 Data A...,"YouTube Data API를 사용하는 프로젝트의 기본 할당량은 일일 10,000...","YouTube Data API를 사용하는 프로젝트의 기본 할당량은 일일 10,000...",0.956510,1.000000,1.00,0.666361,1.000000,1.000000

In [8]:
### RAGAS 평가 실행

# LLM 래퍼 생성
evaluator_llm = ChatOpenAI(model="gpt-4.1-mini", temperature=0)
evaluator_llm = LangchainLLMWrapper(evaluator_llm)

# 평가 메트릭 정의
metrics = [
    LLMContextRecall(),  # 검색된 컨텍스트의 회수율
    Faithfulness(),  # 생성된 답변의 충실도
    FactualCorrectness()  # 사실적 정확성
]
# 평가 실행

result = evaluate(
    dataset=ragas_evaluated_dataset,
    metrics=metrics,
    llm=evaluator_llm,
)

print(result)
# 결과를 DataFrame으로 변환
result_df = result.to_pandas()

# 결과 저장
# result_df.to_csv('ragas_evaluation_result_hybrid4.csv', index=False)

display(result_df.head())
result_df[['context_recall', 'faithfulness', 'factual_correctness(mode=f1)']].describe()

Evaluating:   0%|          | 0/60 [00:00<?, ?it/s]

{'context_recall': 0.9000, 'faithfulness': 0.8478, 'factual_correctness(mode=f1)': 0.6795}

,user_input,retrieved_contexts,response,reference,context_recall,faithfulness,factual_correctness(mode=f1)
0,Analytics Hub 게시자와 목록 관리자 역할의 차이점은 무엇인가요?,[analyticshub.listings.list\n소유자 [https://clou...,Analytics Hub 게시자와 목록 관리자 역할의 차이점은 다음과 같습니다:\n...,"Analytics Hub 게시자 역할은 목록을 생성, 업데이트, 삭제하고 목록에 I...",1.0,1.00,0.93
1,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 어떻게 해...,[탐색기 창에서 프로젝트와 쿼리 폴더를 펼치고 필요한 경우 공유 쿼리 폴더를 펼칩니...,BigQuery Studio 저장된 쿼리에 대한 공개 액세스 권한을 방지하려면 프로...,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 프로젝트에...,1.0,1.00,0.91
2,calendarId에 primary 키워드를 사용하면 어떤 캘린더에 접근할 수 있나요?,[참고: 승인 [https://developers.google.com/workspa...,`calendarId`에 `primary` 키워드를 사용하면 현재 로그인한 사용자의...,calendarId에 primary 키워드를 사용하면 현재 로그인한 사용자의 기본 ...,1.0,1.00,1.00
3,Google Drive API v3의 서비스 엔드포인트가 궁금해,[https://www.googleapis.com/discovery/v1/apis/...,Google Drive API v3의 서비스 엔드포인트는 `https://www.g...,Google Drive API v3의 서비스 엔드포인트는 https://www.go...,1.0,0.50,0.50
4,files.create 메서드의 최대 파일 크기와 허용되는 미디어 MIME 유형은 ...,[이 페이지는 Cloud Translation API [https://cloud.g...,files.create 메서드를 사용하여 파일을 업로드할 때 지원되는 최대 파일 크...,"files.create 메서드의 최대 파일 크기는 5,120GB입니다. 허용되는 미...",1.0,0.75,0.75

       context_recall  faithfulness  factual_correctness(mode=f1)
count       20.000000     20.000000                     20.000000
mean         0.900000      0.847817                      0.679500
std          0.307794      0.206290                      0.277574
min          0.000000      0.428571                      0.000000
25%          1.000000      0.666667                      0.500000
50%          1.000000      1.000000                      0.740000
75%          1.000000      1.000000                      0.910000
max          1.000000      1.000000                      1.000000

In [9]:
display(result_df)

,user_input,retrieved_contexts,response,reference,context_recall,faithfulness,factual_correctness(mode=f1)
0,Analytics Hub 게시자와 목록 관리자 역할의 차이점은 무엇인가요?,[analyticshub.listings.list\n소유자 [https://clou...,Analytics Hub 게시자와 목록 관리자 역할의 차이점은 다음과 같습니다:\n...,"Analytics Hub 게시자 역할은 목록을 생성, 업데이트, 삭제하고 목록에 I...",1.0,1.000000,0.93
1,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 어떻게 해...,[탐색기 창에서 프로젝트와 쿼리 폴더를 펼치고 필요한 경우 공유 쿼리 폴더를 펼칩니...,BigQuery Studio 저장된 쿼리에 대한 공개 액세스 권한을 방지하려면 프로...,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 프로젝트에...,1.0,1.000000,0.91
2,calendarId에 primary 키워드를 사용하면 어떤 캘린더에 접근할 수 있나요?,[참고: 승인 [https://developers.google.com/workspa...,`calendarId`에 `primary` 키워드를 사용하면 현재 로그인한 사용자의...,calendarId에 primary 키워드를 사용하면 현재 로그인한 사용자의 기본 ...,1.0,1.000000,1.00
3,Google Drive API v3의 서비스 엔드포인트가 궁금해,[https://www.googleapis.com/discovery/v1/apis/...,Google Drive API v3의 서비스 엔드포인트는 `https://www.g...,Google Drive API v3의 서비스 엔드포인트는 https://www.go...,1.0,0.500000,0.50
4,files.create 메서드의 최대 파일 크기와 허용되는 미디어 MIME 유형은 ...,[이 페이지는 Cloud Translation API [https://cloud.g...,files.create 메서드를 사용하여 파일을 업로드할 때 지원되는 최대 파일 크...,"files.create 메서드의 최대 파일 크기는 5,120GB입니다. 허용되는 미...",1.0,0.750000,0.75
5,Firebase scrypt 해시 비밀번호를 사용한 사용자 가져오는 방법은?,[Source URL: https://firebase.google.com/docs/...,Firebase scrypt 해시 비밀번호를 사용한 사용자를 가져오는 방법은 다음과...,"Firebase scrypt 해시 비밀번호를 사용한 사용자를 가져오려면, 먼저 Fi...",1.0,1.000000,0.63
6,커스텀 인증 시스템으로 Firebase에 인증하려면 어떻게 해야 하나요?,[Source URL: https://firebase.google.com/docs/...,Firebase에 커스텀 인증 시스템을 통합하려면 다음 단계를 따르세요:\n\n1....,"커스텀 인증 시스템으로 Firebase에 인증하려면, 먼저 인증 서버에서 사용자의 ...",1.0,1.000000,0.59
7,"Firestore에서 맵 필드에 대한 단일 필드 색인 예외를 설정하면, 하위 필드들...",[맵 필드에 단일 필드 색인 예외를 만들면 맵의 하위 필드에서 해당 설정을 상속합니...,"네, Firestore에서 맵 필드에 단일 필드 색인 예외를 설정하면, 맵의 하위 ...","네, Firestore에서 맵 필드에 단일 필드 색인 예외를 만들면 맵의 하위 필드...",1.0,1.000000,0.73
8,Firebase의 updateTime 필드에 사용되는 시간 형식이 뭐야?,[| Fields |\n| --- |\n| name | string The reso...,Firebase의 `updateTime` 필드는 RFC 3339 형식을 사용합니다....,Firebase의 updateTime 필드에는 RFC 3339 시간 형식이 사용됩니...,1.0,1.000000,0.91
9,Firefox 58 환경에서 Gmail의 AMP 렌더링 기능이 호환되나요?,[Source URL: https://developers.google.com/wor...,"네, Firefox 58 환경에서는 Gmail의 AMP 렌더링 기능이 호환됩니다. ...","네, Firefox 58 환경에서는 Gmail의 AMP 렌더링 기능이 호환됩니다. ...",1.0,0.500000,0.80
10,Gmail 자가 테스트를 할 때 DKIM 또는 SPF 인증이 필요해?,[이메일이 SPF (Sender Policy Framework) 인증 [https:...,"자가 테스트를 할 때, 발신자와 수신자가 동일한 계정인 모든 이메일은 등록 요구사항...","네, Gmail 자가 테스트를 할 때 DKIM 또는 SPF 인증이 여전히 필요합니다.",1.0,0.666667,0.50
11,"HTML 헤더에 스크립트 태그를 넣을 수 없을 때, 이메일 본문에 코드를 삽입하는 ...",[이 페이지는 Cloud Translation API [https://cloud.g...,"HTML 헤더에 스크립트 태그를 넣을 수 없는 경우, 이메일 본문에 코드를 삽입하는...","HTML 헤더에 스크립트 태그를 넣을 수 없는 경우, 이메일 본문에 스크립트 태그의...",1.0,1.000000,0.83
12,OAuth에서 승인 사용자 인증 정보 만드는 방법 순서대로 알려주세요.,[사용 설정하려는 API를 선택한 다음 사용 설정 버튼을 클릭합니다.\nIf pro...,OAuth에서 승인 사용자 인증 정보를 만드는 방법은 다음과 같습니다:\n\n1. ...,"OAuth에서 승인 사용자 인증 정보를 만드는 방법은 다음과 같습니다. 먼저, '클...",1.0,1.000000,0.57
13,Google의 계정 간 보안 서비스를 사용하는데 디코딩된 보안 이벤트 토큰의 eve...,[jti 클레임은 단일 보안 이벤트를 식별하는 문자열이며 스트림에 고유합니다. 이 ...,"Google의 계정 간 보안 서비스를 사용할 때, 디코딩된 보안 이벤트 토큰의 `e...",디코딩된 보안 이벤트 토큰의 events 클레임에는 토큰이 나타내는 보안 이벤트에 ...,1.0,1.000000,1.00
14,MAP 3D 스토리텔링의 '표지'를 구성하기 위해 config.json 파일에 직접...,[이 웹 애플리케이션은 3D 환경을 맞춤설정할 수 있는 사용자 친화적인 인터페이스를...,3D 스토리텔링의 '표지'를 구성하기 위해 config.json 파일에 직접 추가할...,MAP 3D 스토리텔링의 '표지'를 구성하기 위해 config.json 파일에 직접...,0.0,0.428571,0.25
15,"GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?",[GMSProjection [https://developers.google.com/...,"죄송하지만, GMSMapPoint의 좌표계에서 (0, 0)이 어떤 지점을 의미하는지...","(0, 0)은 GMSMapPoint 좌표계에서 지도의 중심을 의미합니다.",0.0,0.666667,0.00
16,People API의 RequestMask 필드에 무엇을 입력해야 하나요?,[Source URL: https://developers.google.com/peo...,"People API의 RequestMask 필드는 지원 중단되었습니다. 대신, pe...",지원 중단되었습니다. 대신 personFields를 사용해 주세요.,1.0,0.666667,0.50
17,People API에 요청을 보내는 Python 스크립트를 어떻게 실행하고 구성해야...,[샘플 구성 [https://developers.google.com/people/q...,People API에 요청을 보내는 Python 스크립트를 실행하고 구성하는 방법은...,People API에 요청을 보내는 Python 스크립트를 실행하고 구성하려면 다음...,1.0,1.000000,0.31
18,Google Sheets의 SERIAL_NUMBER 형식으로 1900년 2월 1일 ...,[Source URL: https://developers.google.com/wor...,1900년 2월 1일 오후 5시의 경우 SERIAL_NUMBER 형식으로 계산하면 ...,Google Sheets의 SERIAL_NUMBER 형식에서 1900년 2월 1일 ...,1.0,0.777778,0.88
19,YouTube Data API를 사용하는 프로젝트의 기본 할당량은 얼마인가요?,[YouTube에서 Shorts 동영상의 조회수를 집계하는 방식에 맞게 Data A...,"YouTube Data API를 사용하는 프로젝트의 기본 할당량은 일일 10,000...","YouTube Data API를 사용하는 프로젝트의 기본 할당량은 일일 10,000...",1.0,1.000000,1.00